server:
    port: 3001


spring:
    datasource:
      username: root
      password: password
      url: jdbc:mysql://localhost:3306/test
      driver-class-name: com.mysql.jdbc.Driver


    jpa:
       show-sql: true
       properties:
          hibernate:
              format_sql: true

